export enum Transaction_ID {
    TRANSFER = 0,
    JOIN = 1,
    CLAIM_SPOT = 2,
    DELEGATE = 3,
    WITHDRAW = 4,
    VM_DATA_TXN = 5,
    CLAIM_VM_ID = 6,
    // REMOVE_VALIDATOR = 7,
    SET_GUARDIAN = 8,
    REMOVE_GUARDIAN = 9,
    GUARDIAN_TXN = 10,
    PAYABLE_VM_DATA_TXN = 11,
    CONDUIT_TXN = 12,
    SET_CONDUIT = 13,
    ADD_CONDUITS = 14,
    REMOVE_CONDUITS = 15,
    MOVE_STAKE = 16,

    //
    CHANGE_EARLY_WITHDRAW_PENALTY_PROPOSAL = 17,
    CHANGE_FEE_PER_BYTE_PROPOSAL = 18,
    CHANGE_MAX_BLOCK_SIZE_PROPOSAL = 19,
    CHANGE_MAX_TXN_SIZE_PROPOSAL = 20,
    CHANGE_OVERALL_BURN_PERCENTAGE_PROPOSAL = 21,
    CHANGE_REWARD_PER_YEAR_PROPOSAL_TXN = 22,
    CHANGE_VALIDATOR_COUNT_LIMIT_PROPOSAL = 23,
    CHANGE_VALIDATOR_JOINING_FEE_PROPOSAL = 24,
    CHANGE_VM_ID_CLAIMING_FEE_PROPOSAL = 25,
    CHANGE_VM_OWNER_TXN_FEE_SHARE_PROPOSAL = 26,
    OTHER_PROPOSAL_TXN = 27,
    VOTE_ON_PROPOSAL_TXN = 28,

    // Falcon
    FALCON_SET_PUBLIC_KEY = 1001,
    FALCON_TRANSFER = 1006,

    // proposals
    FALCON_CHANGE_EARLY_WITHDRAW_PENALTY_PROPOSAL = 1009,
    FALCON_CHANGE_FEE_PER_BYTE_PROPOSAL = 1010,
    FALCON_CHANGE_MAX_BLOCK_SIZE_PROPOSAL = 1011,
    FALCON_CHANGE_MAX_TXN_SIZE_PROPOSAL = 1012,
    FALCON_CHANGE_OVERALL_BURN_PERCENTAGE_PROPOSAL = 1013,
    FALCON_CHANGE_REWARD_PER_YEAR_PROPOSAL = 1014,
    FALCON_CHANGE_VALIDATOR_COUNT_LIMIT_PROPOSAL = 1015,
    FALCON_CHANGE_VALIDATOR_JOINING_FEE_PROPOSAL = 1016,
    FALCON_CHANGE_VIDA_ID_CLAIMING_FEE_PROPOSAL = 1017,
    FALCON_CHANGE_VM_OWNER_TXN_FEE_SHARE_PROPOSAL = 1018,
    FALCON_OTHER_PROPOSAL = 1019,
    FALCON_VOTE_ON_PROPOSAL = 1020,

    // guardian
    FALCON_GUARDIAN_APPROVAL = 1021,
    FALCON_REMOVE_GUARDIAN = 1022,
    FALCON_SET_GUARDIAN = 1023,

    // validator
    FALCON_JOIN_AS_VALIDATOR = 1002,
    FALCON_DELEGATE = 1003,
    FALCON_CHANGE_IP = 1004,
    FALCON_ACTIVE_NODE_SPOT = 1005,
    FALCON_MOVE_STAKE_TXN = 1024,
    FALCON_REMOVE_VALIDATOR = 1025,
    FALCON_WITHDRAW = 1026,

    // vida
    FALCON_CLAIM_VIDA_ID = 1028,
    FALCON_PAYABLE_VIDA_DATA = 1030,
    FALCON_SET_VIDA_PRIVATE_STATE = 1034,
    FALCON_SET_VIDA_TO_ABSOLUTE_PUBLIC = 1035,
    FALCON_ADD_VIDA_SPONSORED_ADDRESSES = 1036,
    FALCON_ADD_VIDA_ALLOWED_SENDERS = 1037,
    FALCON_REMOVE_VIDA_ALLOWED_SENDERS = 1038,

    // conduits
    FALCON_CONDUITS_APPROVAL = 1029,
    FALCON_REMOVE_CONDUITS = 1031,
    FALCON_CONDUIT_MODE = 1033,
    FALCON_SET_CONDUIT_MODE_WITH_VIDA_BASED = 1033,

    // others
    FALCON_REMOVE_SPONSORED_ADDRESSES = 1039,
    FALCON_SET_PWR_TRANSFER_RIGHTS = 1040,
    FALCON_TRANSFER_PWR_FROM_VIDA = 1041,
}
